apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: iam-service
    meta.helm.sh/release-namespace: platform-mesh-system
  creationTimestamp: "2026-08-10T12:23:37Z"
  generation: 2
  labels:
    app: iam-service
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: iam-service
    helm.toolkit.fluxcd.io/namespace: platform-mesh-system
  name: iam-service
  namespace: platform-mesh-system
  resourceVersion: "174706"
  uid: 65834379-980a-4e81-995c-354fcf5b0578
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: iam-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-08-10T14:27:10+02:00"
      labels:
        app: iam-service
    spec:
      containers:
      - args:
        - serve
        - --keycloak-base-url=https://ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu/keycloak
        - --keycloak-client-id=iam-service
        - --roles-file-path=/roles/roles.yaml
        - --jwt-user-id-claim=email
        - --no-json
        env:
        - name: KUBECONFIG
          value: /api-kubeconfig/kubeconfig
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client_secret
              name: iam-client-secret
        image: ghcr.io/platform-mesh/platform-mesh/iam-service:v0.18.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: iam-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /api-kubeconfig
          name: external-api-server
        - mountPath: /roles
          name: roles
        - mountPath: /etc/ssl/certs/domain-ca.crt
          name: domain-ca
          readOnly: true
          subPath: tls.crt
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - localhost
        - ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu
        - kcp.localhost
        - root.kcp.localhost
        - kcp.api.ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu
        - nereus.kcp.localhost
        - triton.kcp.localhost
        ip: 100.104.188.4
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: iam-service
      serviceAccountName: iam-service
      terminationGracePeriodSeconds: 30
      volumes:
      - name: external-api-server
        secret:
          defaultMode: 420
          secretName: iam-service-kubeconfig
      - configMap:
          defaultMode: 420
          name: iam-service-roles
        name: roles
      - name: domain-ca
        secret:
          defaultMode: 420
          secretName: domain-certificate-ca
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-08-10T12:23:49Z"
    lastUpdateTime: "2026-08-10T12:23:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-08-10T12:23:37Z"
    lastUpdateTime: "2026-08-10T12:27:22Z"
    message: ReplicaSet "iam-service-6cbf97fd4b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
