apiVersion: v1
items:
- apiVersion: tenancy.kcp.io/v1alpha1
  kind: WorkspaceAuthenticationConfiguration
  metadata:
    annotations:
      kcp.io/cluster: 84l5c58301f7e4s2
    creationTimestamp: "2026-08-11T06:41:01Z"
    generation: 1
    name: aitrustdemo
    resourceVersion: "45662"
    uid: c16777d1-8bb3-4c92-a591-95764d4de850
  spec:
    jwt:
    - claimMappings:
        groups:
          claim: groups
          prefix: ""
        uid: {}
        username:
          expression: claims.email
      claimValidationRules:
      - expression: claims.?email_verified.orValue(true) == true || claims.?email_verified.orValue(true)
          == false
        message: Allowing both verified and unverified emails
      issuer:
        audienceMatchPolicy: MatchAny
        audiences:
        - 0ae264df-14c5-473b-89ba-17a721d03920
        - 910a5139-6667-46d2-b199-dc4055ae709f
        certificateAuthority: |
          -----BEGIN CERTIFICATE-----
          MIIDNTCCAh2gAwIBAgIULXjNvdjr5NFFtopXpmr26ixpLLgwDQYJKoZIhvcNAQEL
          BQAwKjEoMCYGA1UEAwwfU3RhbmRhcmQgUGxhdGZvcm0gTWVzaCBMb2NhbCBDQTAe
          Fw0yNjA4MTAxMTE5MDhaFw0yODExMTIxMTE5MDhaMCoxKDAmBgNVBAMMH1N0YW5k
          YXJkIFBsYXRmb3JtIE1lc2ggTG9jYWwgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
          DwAwggEKAoIBAQDCzzrIn244EO+Pejof2D1F9EYm+zvhahyVTzyDdL3fBopQ6q9c
          jhMqInqQb6Gk8XpemPJMvBPFAyuT+DCi55OGg0QOTuBsicB7ai9RIC9rrKXy8YUs
          2dmRIHaGJb4Q5VU5H7B9MoxJMONgHJ19LONmrbR8X8PvTMBPUlEfKV2KVMhjXXtp
          46vyCgbL+KGWY/f1OKIHDhJM7NpuJDkybi0RYWaIZuRl2erOgcme7POptWOCcZ0/
          Npv1RFeqW5S6lKfqA+XW2tVIUEVwCL5X5By2kmEAdCQ3iSDr/+3fXRH4T0DSz4wr
          SSXyINSv5rCxBIxgqX1RnLiI7ePEKCyGw4fnAgMBAAGjUzBRMB0GA1UdDgQWBBRb
          Dey0rQOdQrtiqaZIeg1XRvmBUDAfBgNVHSMEGDAWgBRbDey0rQOdQrtiqaZIeg1X
          RvmBUDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAleIXFiTxx
          RtYHE6o7XMMcZQEuWG7t/4mUG28C60FDXoWwQQNJ+FBXxgkUPB60PclVKDStWHn5
          hE6qNomhd78cvQHdOS/L3p14VypUevswPAe5/UGyryqVraqoZss0KmUGoJgPvQVU
          bZJdE0tj5XW8n3EexrZ0nWwTCt086/yVpJzmncuEeuZkk+nRVG6WoJLXcVoY4zlx
          Oic+OXQIBoT+Umgrp2ohcr/5ibLzEyPpATYrHDhebi5T+TiOizY44cTxUZrFPUDC
          S4fQyiskOa+S28MOdofQik294hGL/PrrZ64X1EQHpdkno4D3y0Kk3KjRvrRPgBRU
          kEeUb1ZMoe6j
          -----END CERTIFICATE-----
        url: https://ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu/keycloak/realms/aitrustdemo
- apiVersion: tenancy.kcp.io/v1alpha1
  kind: WorkspaceAuthenticationConfiguration
  metadata:
    annotations:
      kcp.io/cluster: 84l5c58301f7e4s2
    creationTimestamp: "2026-08-11T10:07:02Z"
    generation: 1
    name: aitrustfresh
    resourceVersion: "59809"
    uid: 5b4b3b4f-d775-42f0-8dc4-72aadc2e2fac
  spec:
    jwt:
    - claimMappings:
        groups:
          claim: groups
          prefix: ""
        uid: {}
        username:
          expression: claims.email
      claimValidationRules:
      - expression: claims.?email_verified.orValue(true) == true || claims.?email_verified.orValue(true)
          == false
        message: Allowing both verified and unverified emails
      issuer:
        audienceMatchPolicy: MatchAny
        audiences:
        - ae38a82b-883e-4f71-a460-b9664f2a3975
        - 63dcebea-3b0c-40e3-8d6f-34584992b68a
        certificateAuthority: |
          -----BEGIN CERTIFICATE-----
          MIIDNTCCAh2gAwIBAgIULXjNvdjr5NFFtopXpmr26ixpLLgwDQYJKoZIhvcNAQEL
          BQAwKjEoMCYGA1UEAwwfU3RhbmRhcmQgUGxhdGZvcm0gTWVzaCBMb2NhbCBDQTAe
          Fw0yNjA4MTAxMTE5MDhaFw0yODExMTIxMTE5MDhaMCoxKDAmBgNVBAMMH1N0YW5k
          YXJkIFBsYXRmb3JtIE1lc2ggTG9jYWwgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
          DwAwggEKAoIBAQDCzzrIn244EO+Pejof2D1F9EYm+zvhahyVTzyDdL3fBopQ6q9c
          jhMqInqQb6Gk8XpemPJMvBPFAyuT+DCi55OGg0QOTuBsicB7ai9RIC9rrKXy8YUs
          2dmRIHaGJb4Q5VU5H7B9MoxJMONgHJ19LONmrbR8X8PvTMBPUlEfKV2KVMhjXXtp
          46vyCgbL+KGWY/f1OKIHDhJM7NpuJDkybi0RYWaIZuRl2erOgcme7POptWOCcZ0/
          Npv1RFeqW5S6lKfqA+XW2tVIUEVwCL5X5By2kmEAdCQ3iSDr/+3fXRH4T0DSz4wr
          SSXyINSv5rCxBIxgqX1RnLiI7ePEKCyGw4fnAgMBAAGjUzBRMB0GA1UdDgQWBBRb
          Dey0rQOdQrtiqaZIeg1XRvmBUDAfBgNVHSMEGDAWgBRbDey0rQOdQrtiqaZIeg1X
          RvmBUDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAleIXFiTxx
          RtYHE6o7XMMcZQEuWG7t/4mUG28C60FDXoWwQQNJ+FBXxgkUPB60PclVKDStWHn5
          hE6qNomhd78cvQHdOS/L3p14VypUevswPAe5/UGyryqVraqoZss0KmUGoJgPvQVU
          bZJdE0tj5XW8n3EexrZ0nWwTCt086/yVpJzmncuEeuZkk+nRVG6WoJLXcVoY4zlx
          Oic+OXQIBoT+Umgrp2ohcr/5ibLzEyPpATYrHDhebi5T+TiOizY44cTxUZrFPUDC
          S4fQyiskOa+S28MOdofQik294hGL/PrrZ64X1EQHpdkno4D3y0Kk3KjRvrRPgBRU
          kEeUb1ZMoe6j
          -----END CERTIFICATE-----
        url: https://ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu/keycloak/realms/aitrustfresh
- apiVersion: tenancy.kcp.io/v1alpha1
  kind: WorkspaceAuthenticationConfiguration
  metadata:
    annotations:
      kcp.io/cluster: 84l5c58301f7e4s2
    creationTimestamp: "2026-08-11T10:34:25Z"
    generation: 2
    name: aitrustg2
    resourceVersion: "61229"
    uid: 395d5edf-b890-48fd-a16c-3532da9581cd
  spec:
    jwt:
    - claimMappings:
        groups:
          claim: groups
          prefix: ""
        uid: {}
        username:
          expression: claims.email
      claimValidationRules:
      - expression: claims.?email_verified.orValue(true) == true || claims.?email_verified.orValue(true)
          == false
        message: Allowing both verified and unverified emails
      issuer:
        audienceMatchPolicy: MatchAny
        audiences:
        - 7cc28526-07e0-4f84-9d1c-d573d09285fb
        - 2117b824-b4f1-410a-b9d7-c08913fe71c4
        certificateAuthority: |
          -----BEGIN CERTIFICATE-----
          MIIDNTCCAh2gAwIBAgIULXjNvdjr5NFFtopXpmr26ixpLLgwDQYJKoZIhvcNAQEL
          BQAwKjEoMCYGA1UEAwwfU3RhbmRhcmQgUGxhdGZvcm0gTWVzaCBMb2NhbCBDQTAe
          Fw0yNjA4MTAxMTE5MDhaFw0yODExMTIxMTE5MDhaMCoxKDAmBgNVBAMMH1N0YW5k
          YXJkIFBsYXRmb3JtIE1lc2ggTG9jYWwgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
          DwAwggEKAoIBAQDCzzrIn244EO+Pejof2D1F9EYm+zvhahyVTzyDdL3fBopQ6q9c
          jhMqInqQb6Gk8XpemPJMvBPFAyuT+DCi55OGg0QOTuBsicB7ai9RIC9rrKXy8YUs
          2dmRIHaGJb4Q5VU5H7B9MoxJMONgHJ19LONmrbR8X8PvTMBPUlEfKV2KVMhjXXtp
          46vyCgbL+KGWY/f1OKIHDhJM7NpuJDkybi0RYWaIZuRl2erOgcme7POptWOCcZ0/
          Npv1RFeqW5S6lKfqA+XW2tVIUEVwCL5X5By2kmEAdCQ3iSDr/+3fXRH4T0DSz4wr
          SSXyINSv5rCxBIxgqX1RnLiI7ePEKCyGw4fnAgMBAAGjUzBRMB0GA1UdDgQWBBRb
          Dey0rQOdQrtiqaZIeg1XRvmBUDAfBgNVHSMEGDAWgBRbDey0rQOdQrtiqaZIeg1X
          RvmBUDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAleIXFiTxx
          RtYHE6o7XMMcZQEuWG7t/4mUG28C60FDXoWwQQNJ+FBXxgkUPB60PclVKDStWHn5
          hE6qNomhd78cvQHdOS/L3p14VypUevswPAe5/UGyryqVraqoZss0KmUGoJgPvQVU
          bZJdE0tj5XW8n3EexrZ0nWwTCt086/yVpJzmncuEeuZkk+nRVG6WoJLXcVoY4zlx
          Oic+OXQIBoT+Umgrp2ohcr/5ibLzEyPpATYrHDhebi5T+TiOizY44cTxUZrFPUDC
          S4fQyiskOa+S28MOdofQik294hGL/PrrZ64X1EQHpdkno4D3y0Kk3KjRvrRPgBRU
          kEeUb1ZMoe6j
          -----END CERTIFICATE-----
        url: https://ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu/keycloak/realms/aitrustg2
- apiVersion: tenancy.kcp.io/v1alpha1
  kind: WorkspaceAuthenticationConfiguration
  metadata:
    annotations:
      kcp.io/cluster: 84l5c58301f7e4s2
    creationTimestamp: "2026-08-10T15:18:34Z"
    generation: 1
    name: demo
    resourceVersion: "10582"
    uid: 88a55249-371a-4869-8369-4f834bad6a61
  spec:
    jwt:
    - claimMappings:
        groups:
          claim: groups
          prefix: ""
        uid: {}
        username:
          expression: claims.email
      claimValidationRules:
      - expression: claims.?email_verified.orValue(true) == true || claims.?email_verified.orValue(true)
          == false
        message: Allowing both verified and unverified emails
      issuer:
        audienceMatchPolicy: MatchAny
        audiences:
        - b8a2730a-5891-4c27-83e0-264a42e97627
        - dbcfa7b1-223b-4d91-a873-8d0e1403761c
        certificateAuthority: |
          -----BEGIN CERTIFICATE-----
          MIIDNTCCAh2gAwIBAgIULXjNvdjr5NFFtopXpmr26ixpLLgwDQYJKoZIhvcNAQEL
          BQAwKjEoMCYGA1UEAwwfU3RhbmRhcmQgUGxhdGZvcm0gTWVzaCBMb2NhbCBDQTAe
          Fw0yNjA4MTAxMTE5MDhaFw0yODExMTIxMTE5MDhaMCoxKDAmBgNVBAMMH1N0YW5k
          YXJkIFBsYXRmb3JtIE1lc2ggTG9jYWwgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
          DwAwggEKAoIBAQDCzzrIn244EO+Pejof2D1F9EYm+zvhahyVTzyDdL3fBopQ6q9c
          jhMqInqQb6Gk8XpemPJMvBPFAyuT+DCi55OGg0QOTuBsicB7ai9RIC9rrKXy8YUs
          2dmRIHaGJb4Q5VU5H7B9MoxJMONgHJ19LONmrbR8X8PvTMBPUlEfKV2KVMhjXXtp
          46vyCgbL+KGWY/f1OKIHDhJM7NpuJDkybi0RYWaIZuRl2erOgcme7POptWOCcZ0/
          Npv1RFeqW5S6lKfqA+XW2tVIUEVwCL5X5By2kmEAdCQ3iSDr/+3fXRH4T0DSz4wr
          SSXyINSv5rCxBIxgqX1RnLiI7ePEKCyGw4fnAgMBAAGjUzBRMB0GA1UdDgQWBBRb
          Dey0rQOdQrtiqaZIeg1XRvmBUDAfBgNVHSMEGDAWgBRbDey0rQOdQrtiqaZIeg1X
          RvmBUDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAleIXFiTxx
          RtYHE6o7XMMcZQEuWG7t/4mUG28C60FDXoWwQQNJ+FBXxgkUPB60PclVKDStWHn5
          hE6qNomhd78cvQHdOS/L3p14VypUevswPAe5/UGyryqVraqoZss0KmUGoJgPvQVU
          bZJdE0tj5XW8n3EexrZ0nWwTCt086/yVpJzmncuEeuZkk+nRVG6WoJLXcVoY4zlx
          Oic+OXQIBoT+Umgrp2ohcr/5ibLzEyPpATYrHDhebi5T+TiOizY44cTxUZrFPUDC
          S4fQyiskOa+S28MOdofQik294hGL/PrrZ64X1EQHpdkno4D3y0Kk3KjRvrRPgBRU
          kEeUb1ZMoe6j
          -----END CERTIFICATE-----
        url: https://ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu/keycloak/realms/demo
- apiVersion: tenancy.kcp.io/v1alpha1
  kind: WorkspaceAuthenticationConfiguration
  metadata:
    annotations:
      kcp.io/cluster: 84l5c58301f7e4s2
    creationTimestamp: "2026-08-10T12:49:53Z"
    generation: 3
    name: mirceatest
    resourceVersion: "4979"
    uid: 0ea31f06-26a4-4e35-8297-4f74a93ec251
  spec:
    jwt:
    - claimMappings:
        groups:
          claim: groups
          prefix: ""
        uid: {}
        username:
          expression: claims.email
      claimValidationRules:
      - expression: claims.?email_verified.orValue(true) == true || claims.?email_verified.orValue(true)
          == false
        message: Allowing both verified and unverified emails
      issuer:
        audienceMatchPolicy: MatchAny
        audiences:
        - 76491e2a-f078-49a2-8acb-bd238f5e1ed9
        - 5c0975eb-cf52-48de-a13b-2ecbf38b0460
        certificateAuthority: |
          -----BEGIN CERTIFICATE-----
          MIIDNTCCAh2gAwIBAgIULXjNvdjr5NFFtopXpmr26ixpLLgwDQYJKoZIhvcNAQEL
          BQAwKjEoMCYGA1UEAwwfU3RhbmRhcmQgUGxhdGZvcm0gTWVzaCBMb2NhbCBDQTAe
          Fw0yNjA4MTAxMTE5MDhaFw0yODExMTIxMTE5MDhaMCoxKDAmBgNVBAMMH1N0YW5k
          YXJkIFBsYXRmb3JtIE1lc2ggTG9jYWwgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
          DwAwggEKAoIBAQDCzzrIn244EO+Pejof2D1F9EYm+zvhahyVTzyDdL3fBopQ6q9c
          jhMqInqQb6Gk8XpemPJMvBPFAyuT+DCi55OGg0QOTuBsicB7ai9RIC9rrKXy8YUs
          2dmRIHaGJb4Q5VU5H7B9MoxJMONgHJ19LONmrbR8X8PvTMBPUlEfKV2KVMhjXXtp
          46vyCgbL+KGWY/f1OKIHDhJM7NpuJDkybi0RYWaIZuRl2erOgcme7POptWOCcZ0/
          Npv1RFeqW5S6lKfqA+XW2tVIUEVwCL5X5By2kmEAdCQ3iSDr/+3fXRH4T0DSz4wr
          SSXyINSv5rCxBIxgqX1RnLiI7ePEKCyGw4fnAgMBAAGjUzBRMB0GA1UdDgQWBBRb
          Dey0rQOdQrtiqaZIeg1XRvmBUDAfBgNVHSMEGDAWgBRbDey0rQOdQrtiqaZIeg1X
          RvmBUDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAleIXFiTxx
          RtYHE6o7XMMcZQEuWG7t/4mUG28C60FDXoWwQQNJ+FBXxgkUPB60PclVKDStWHn5
          hE6qNomhd78cvQHdOS/L3p14VypUevswPAe5/UGyryqVraqoZss0KmUGoJgPvQVU
          bZJdE0tj5XW8n3EexrZ0nWwTCt086/yVpJzmncuEeuZkk+nRVG6WoJLXcVoY4zlx
          Oic+OXQIBoT+Umgrp2ohcr/5ibLzEyPpATYrHDhebi5T+TiOizY44cTxUZrFPUDC
          S4fQyiskOa+S28MOdofQik294hGL/PrrZ64X1EQHpdkno4D3y0Kk3KjRvrRPgBRU
          kEeUb1ZMoe6j
          -----END CERTIFICATE-----
        url: https://ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu/keycloak/realms/mirceatest
- apiVersion: tenancy.kcp.io/v1alpha1
  kind: WorkspaceAuthenticationConfiguration
  metadata:
    annotations:
      kcp.io/cluster: 84l5c58301f7e4s2
    creationTimestamp: "2026-08-10T16:26:35Z"
    generation: 6
    name: mirceatest2
    resourceVersion: "19729"
    uid: 6feae554-6712-4d83-b397-2579577ad3de
  spec:
    jwt:
    - claimMappings:
        groups:
          claim: groups
          prefix: ""
        uid: {}
        username:
          expression: claims.email
      claimValidationRules:
      - expression: claims.?email_verified.orValue(true) == true || claims.?email_verified.orValue(true)
          == false
        message: Allowing both verified and unverified emails
      issuer:
        audienceMatchPolicy: MatchAny
        audiences:
        - 458a061a-256d-4174-b306-ccdfc982725e
        - 75d078b2-6d10-4c3e-ac60-386f052966b2
        certificateAuthority: |
          -----BEGIN CERTIFICATE-----
          MIIDNTCCAh2gAwIBAgIULXjNvdjr5NFFtopXpmr26ixpLLgwDQYJKoZIhvcNAQEL
          BQAwKjEoMCYGA1UEAwwfU3RhbmRhcmQgUGxhdGZvcm0gTWVzaCBMb2NhbCBDQTAe
          Fw0yNjA4MTAxMTE5MDhaFw0yODExMTIxMTE5MDhaMCoxKDAmBgNVBAMMH1N0YW5k
          YXJkIFBsYXRmb3JtIE1lc2ggTG9jYWwgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
          DwAwggEKAoIBAQDCzzrIn244EO+Pejof2D1F9EYm+zvhahyVTzyDdL3fBopQ6q9c
          jhMqInqQb6Gk8XpemPJMvBPFAyuT+DCi55OGg0QOTuBsicB7ai9RIC9rrKXy8YUs
          2dmRIHaGJb4Q5VU5H7B9MoxJMONgHJ19LONmrbR8X8PvTMBPUlEfKV2KVMhjXXtp
          46vyCgbL+KGWY/f1OKIHDhJM7NpuJDkybi0RYWaIZuRl2erOgcme7POptWOCcZ0/
          Npv1RFeqW5S6lKfqA+XW2tVIUEVwCL5X5By2kmEAdCQ3iSDr/+3fXRH4T0DSz4wr
          SSXyINSv5rCxBIxgqX1RnLiI7ePEKCyGw4fnAgMBAAGjUzBRMB0GA1UdDgQWBBRb
          Dey0rQOdQrtiqaZIeg1XRvmBUDAfBgNVHSMEGDAWgBRbDey0rQOdQrtiqaZIeg1X
          RvmBUDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAleIXFiTxx
          RtYHE6o7XMMcZQEuWG7t/4mUG28C60FDXoWwQQNJ+FBXxgkUPB60PclVKDStWHn5
          hE6qNomhd78cvQHdOS/L3p14VypUevswPAe5/UGyryqVraqoZss0KmUGoJgPvQVU
          bZJdE0tj5XW8n3EexrZ0nWwTCt086/yVpJzmncuEeuZkk+nRVG6WoJLXcVoY4zlx
          Oic+OXQIBoT+Umgrp2ohcr/5ibLzEyPpATYrHDhebi5T+TiOizY44cTxUZrFPUDC
          S4fQyiskOa+S28MOdofQik294hGL/PrrZ64X1EQHpdkno4D3y0Kk3KjRvrRPgBRU
          kEeUb1ZMoe6j
          -----END CERTIFICATE-----
        url: https://ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu/keycloak/realms/mirceatest2
- apiVersion: tenancy.kcp.io/v1alpha1
  kind: WorkspaceAuthenticationConfiguration
  metadata:
    annotations:
      kcp.io/cluster: 84l5c58301f7e4s2
    creationTimestamp: "2026-08-11T08:24:31Z"
    generation: 1
    name: mirceatest3
    resourceVersion: "53070"
    uid: f1c0ab27-7671-414f-96ed-a45803dd5db6
  spec:
    jwt:
    - claimMappings:
        groups:
          claim: groups
          prefix: ""
        uid: {}
        username:
          expression: claims.email
      claimValidationRules:
      - expression: claims.?email_verified.orValue(true) == true || claims.?email_verified.orValue(true)
          == false
        message: Allowing both verified and unverified emails
      issuer:
        audienceMatchPolicy: MatchAny
        audiences:
        - 024efa71-c1e5-44a1-9122-c425881e5fbd
        - b5ee53f0-ea39-4572-a503-516fe7cae0de
        certificateAuthority: |
          -----BEGIN CERTIFICATE-----
          MIIDNTCCAh2gAwIBAgIULXjNvdjr5NFFtopXpmr26ixpLLgwDQYJKoZIhvcNAQEL
          BQAwKjEoMCYGA1UEAwwfU3RhbmRhcmQgUGxhdGZvcm0gTWVzaCBMb2NhbCBDQTAe
          Fw0yNjA4MTAxMTE5MDhaFw0yODExMTIxMTE5MDhaMCoxKDAmBgNVBAMMH1N0YW5k
          YXJkIFBsYXRmb3JtIE1lc2ggTG9jYWwgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
          DwAwggEKAoIBAQDCzzrIn244EO+Pejof2D1F9EYm+zvhahyVTzyDdL3fBopQ6q9c
          jhMqInqQb6Gk8XpemPJMvBPFAyuT+DCi55OGg0QOTuBsicB7ai9RIC9rrKXy8YUs
          2dmRIHaGJb4Q5VU5H7B9MoxJMONgHJ19LONmrbR8X8PvTMBPUlEfKV2KVMhjXXtp
          46vyCgbL+KGWY/f1OKIHDhJM7NpuJDkybi0RYWaIZuRl2erOgcme7POptWOCcZ0/
          Npv1RFeqW5S6lKfqA+XW2tVIUEVwCL5X5By2kmEAdCQ3iSDr/+3fXRH4T0DSz4wr
          SSXyINSv5rCxBIxgqX1RnLiI7ePEKCyGw4fnAgMBAAGjUzBRMB0GA1UdDgQWBBRb
          Dey0rQOdQrtiqaZIeg1XRvmBUDAfBgNVHSMEGDAWgBRbDey0rQOdQrtiqaZIeg1X
          RvmBUDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAleIXFiTxx
          RtYHE6o7XMMcZQEuWG7t/4mUG28C60FDXoWwQQNJ+FBXxgkUPB60PclVKDStWHn5
          hE6qNomhd78cvQHdOS/L3p14VypUevswPAe5/UGyryqVraqoZss0KmUGoJgPvQVU
          bZJdE0tj5XW8n3EexrZ0nWwTCt086/yVpJzmncuEeuZkk+nRVG6WoJLXcVoY4zlx
          Oic+OXQIBoT+Umgrp2ohcr/5ibLzEyPpATYrHDhebi5T+TiOizY44cTxUZrFPUDC
          S4fQyiskOa+S28MOdofQik294hGL/PrrZ64X1EQHpdkno4D3y0Kk3KjRvrRPgBRU
          kEeUb1ZMoe6j
          -----END CERTIFICATE-----
        url: https://ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu/keycloak/realms/mirceatest3
- apiVersion: tenancy.kcp.io/v1alpha1
  kind: WorkspaceAuthenticationConfiguration
  metadata:
    annotations:
      kcp.io/cluster: 84l5c58301f7e4s2
    creationTimestamp: "2026-08-12T06:26:05Z"
    generation: 2
    name: poc
    resourceVersion: "132785"
    uid: a160375b-5e4e-4ac7-a174-5b065e5c55b3
  spec:
    jwt:
    - claimMappings:
        groups:
          claim: groups
          prefix: ""
        uid: {}
        username:
          expression: claims.email
      claimValidationRules:
      - expression: claims.?email_verified.orValue(true) == true || claims.?email_verified.orValue(true)
          == false
        message: Allowing both verified and unverified emails
      issuer:
        audienceMatchPolicy: MatchAny
        audiences:
        - d1ce81ce-a2fe-43a8-8bd0-534686d3e84f
        - 3bea509e-4616-4682-8cb7-e9bfbe6a3607
        certificateAuthority: |
          -----BEGIN CERTIFICATE-----
          MIIDNTCCAh2gAwIBAgIULXjNvdjr5NFFtopXpmr26ixpLLgwDQYJKoZIhvcNAQEL
          BQAwKjEoMCYGA1UEAwwfU3RhbmRhcmQgUGxhdGZvcm0gTWVzaCBMb2NhbCBDQTAe
          Fw0yNjA4MTAxMTE5MDhaFw0yODExMTIxMTE5MDhaMCoxKDAmBgNVBAMMH1N0YW5k
          YXJkIFBsYXRmb3JtIE1lc2ggTG9jYWwgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
          DwAwggEKAoIBAQDCzzrIn244EO+Pejof2D1F9EYm+zvhahyVTzyDdL3fBopQ6q9c
          jhMqInqQb6Gk8XpemPJMvBPFAyuT+DCi55OGg0QOTuBsicB7ai9RIC9rrKXy8YUs
          2dmRIHaGJb4Q5VU5H7B9MoxJMONgHJ19LONmrbR8X8PvTMBPUlEfKV2KVMhjXXtp
          46vyCgbL+KGWY/f1OKIHDhJM7NpuJDkybi0RYWaIZuRl2erOgcme7POptWOCcZ0/
          Npv1RFeqW5S6lKfqA+XW2tVIUEVwCL5X5By2kmEAdCQ3iSDr/+3fXRH4T0DSz4wr
          SSXyINSv5rCxBIxgqX1RnLiI7ePEKCyGw4fnAgMBAAGjUzBRMB0GA1UdDgQWBBRb
          Dey0rQOdQrtiqaZIeg1XRvmBUDAfBgNVHSMEGDAWgBRbDey0rQOdQrtiqaZIeg1X
          RvmBUDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAleIXFiTxx
          RtYHE6o7XMMcZQEuWG7t/4mUG28C60FDXoWwQQNJ+FBXxgkUPB60PclVKDStWHn5
          hE6qNomhd78cvQHdOS/L3p14VypUevswPAe5/UGyryqVraqoZss0KmUGoJgPvQVU
          bZJdE0tj5XW8n3EexrZ0nWwTCt086/yVpJzmncuEeuZkk+nRVG6WoJLXcVoY4zlx
          Oic+OXQIBoT+Umgrp2ohcr/5ibLzEyPpATYrHDhebi5T+TiOizY44cTxUZrFPUDC
          S4fQyiskOa+S28MOdofQik294hGL/PrrZ64X1EQHpdkno4D3y0Kk3KjRvrRPgBRU
          kEeUb1ZMoe6j
          -----END CERTIFICATE-----
        url: https://ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu/keycloak/realms/poc
kind: List
metadata:
  resourceVersion: ""
