apiVersion: v1
items:
- apiVersion: tenancy.kcp.io/v1alpha1
  kind: WorkspaceAuthenticationConfiguration
  metadata:
    annotations:
      kcp.io/cluster: root
    creationTimestamp: "2026-08-10T11:54:29Z"
    generation: 3
    name: orgs-authentication
    resourceVersion: "4416"
    uid: ca240d07-a0ee-46fa-aebe-950edf10aa4d
  spec:
    jwt:
    - claimMappings:
        groups:
          claim: groups
          prefix: ""
        username:
          expression: claims.email
      claimValidationRules:
      - expression: claims.?email_verified.orValue(true) == true || claims.?email_verified.orValue(true)
          == false
        message: Allowing both verified and unverified emails
      issuer:
        audienceMatchPolicy: MatchAny
        audiences:
        - 81f37072-5716-4fcc-bc38-4cbf506f910d
        - 7053a24b-8a05-445e-b657-c22bfa786e30
        certificateAuthority: |
          -----BEGIN CERTIFICATE-----
          MIIDNTCCAh2gAwIBAgIULXjNvdjr5NFFtopXpmr26ixpLLgwDQYJKoZIhvcNAQEL
          BQAwKjEoMCYGA1UEAwwfU3RhbmRhcmQgUGxhdGZvcm0gTWVzaCBMb2NhbCBDQTAe
          Fw0yNjA4MTAxMTE5MDhaFw0yODExMTIxMTE5MDhaMCoxKDAmBgNVBAMMH1N0YW5k
          YXJkIFBsYXRmb3JtIE1lc2ggTG9jYWwgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
          DwAwggEKAoIBAQDCzzrIn244EO+Pejof2D1F9EYm+zvhahyVTzyDdL3fBopQ6q9c
          jhMqInqQb6Gk8XpemPJMvBPFAyuT+DCi55OGg0QOTuBsicB7ai9RIC9rrKXy8YUs
          2dmRIHaGJb4Q5VU5H7B9MoxJMONgHJ19LONmrbR8X8PvTMBPUlEfKV2KVMhjXXtp
          46vyCgbL+KGWY/f1OKIHDhJM7NpuJDkybi0RYWaIZuRl2erOgcme7POptWOCcZ0/
          Npv1RFeqW5S6lKfqA+XW2tVIUEVwCL5X5By2kmEAdCQ3iSDr/+3fXRH4T0DSz4wr
          SSXyINSv5rCxBIxgqX1RnLiI7ePEKCyGw4fnAgMBAAGjUzBRMB0GA1UdDgQWBBRb
          Dey0rQOdQrtiqaZIeg1XRvmBUDAfBgNVHSMEGDAWgBRbDey0rQOdQrtiqaZIeg1X
          RvmBUDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAleIXFiTxx
          RtYHE6o7XMMcZQEuWG7t/4mUG28C60FDXoWwQQNJ+FBXxgkUPB60PclVKDStWHn5
          hE6qNomhd78cvQHdOS/L3p14VypUevswPAe5/UGyryqVraqoZss0KmUGoJgPvQVU
          bZJdE0tj5XW8n3EexrZ0nWwTCt086/yVpJzmncuEeuZkk+nRVG6WoJLXcVoY4zlx
          Oic+OXQIBoT+Umgrp2ohcr/5ibLzEyPpATYrHDhebi5T+TiOizY44cTxUZrFPUDC
          S4fQyiskOa+S28MOdofQik294hGL/PrrZ64X1EQHpdkno4D3y0Kk3KjRvrRPgBRU
          kEeUb1ZMoe6j
          -----END CERTIFICATE-----
        url: https://ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu/keycloak/realms/welcome
kind: List
metadata:
  resourceVersion: ""
