kind: Config
apiVersion: v1
clusters:
  - name: garden-ai-trust
    cluster:
      server: https://api.garden.gardener.cc-one.showroom.apeirora.eu
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQrRENDQW1DZ0F3SUJBZ0lRVTV6OXhtVUNyNFI5bnQzcWIwZWR1VEFOQmdrcWhraUc5dzBCQVFzRkFEQVcKTVJRd0VnWURWUVFERXd0allTMW1OakF6TW1WaE1EQWVGdzB5TkRFeU1Ua3hOREF4TURSYUZ3MHpOREV5TVRreApOREF5TURSYU1CWXhGREFTQmdOVkJBTVRDMk5oTFdZMk1ETXlaV0V3TUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBWThBTUlJQmlnS0NBWUVBckZKNUZ4WWdVSm1KZEZ0ZXpDZVpDUENweTBzOW9VaEU1QXJudmo1bUlFdHEKbzNuRXVtcGl4WjA4YlhYdUZEcGF1WTlaMC9NcWdyd1B1WC91VHlReGcrOGJXdUZIV0dTaWVpajF6WDA1eW01TgpiQlNZcjJyM2VDaG1lakhWR0V0eVlZd3RCbnRNUVRucnFKeFBUUnFDTmVXcDFkRWpRRGRWYWFjby9LWXEzN01ICkFJQnpxN2lrTTFic3pGYjVUSEJROCt5WldoMlNvTm9md0p1SGV3REpjQS9iQmxnNVNnRVFiWS82UjUxcmppZWwKRVRzTmtYLzIzSHVDT3Z4NWVDRXVoRkRaUXU4WEg3anBpV2l4alJSdE5oK0ZRNVZuMEcrcm45RU9wVEtqc3JWaApmc2lXVXVOQU84dEdoNXlqZmxCdHJlT0hDQS9mangyZTFRa3JkMitUdkt1SDEzRWdjN0lhS2pGeTdrWVhUNjlUCnNMQkE3bk1Ba2o1aTM4emZMakhvcHZmSU52SHZGK0VLalBGd1A0WjBLTUE0aVhlNU5QR0VhWkw1QnpUSERHMzEKQzlqUjQrUWhJSVZhVGZ2SG9UYUJrQUxVdlJyQjFFdy96dkwreVZTQVBqQkZlUDZtZ3FucnViQmRLN0tScFRSOQpZRW56dzdwbWpUT2E1ZG9qcVg1REFnTUJBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CCkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCUXZxcTRFdFNpa3VJaXRrTzlLUTkyb0NJU2E5akFOQmdrcWhraUcKOXcwQkFRc0ZBQU9DQVlFQWswUHJIU1poVHdUaFBZSXVzN2RmbW1tMU5wbGtVenZXV3o3QVFXMUNkK0JQU2Vocwp0WVROM3kwODhRdGVGY3M2Vk1YN0dqMXd3L1VqNkpaNkZzWmlsSHlZRy9MTE1rSUpKdHFNdG0xbmtGZEpEOUc5CmIzelQybXNVTWNqa3kvaUkrYWYzc2V3OWRoOWZtS3NYUFFHRFhCeUxQbkR6SE9uOUNRU2RxbE1aSGdqVFlvODIKM3RFVDUwOWc5c2lMSW8zQmFoSkJYVkxtMEwzbVRqb1RkZmc3QlhmNnd3ZHRJSGplNUkzdTd2VGQvblFnT0N1VwpyWEtZTnRZbDZmRTBYc3hHbTFVYndESTltbG5qRjUyR2xMU0IwMFlFcEhmOHFreWtxNEpMcFhGN3RReTZueW9DCmpDTkxhYkdpUUt4dFhucnNVc3Brc1FNU1U2U3JHSExjaEVjV2RCT09pcThBc0FkR0VHdng3RFZvNmFXc1BvWVoKYVNRYTRGSVNUZDA1eFFUK3JRQ2s4emc2SlRqaEdmZHdJdzRpSXRRTEMyZmNnYzVKUGxLWU5hcDIrU0NSWHB0NApzL0FBVkg0R0JmcE03U3F0cG9XVFZuZnBtVkNwRXRRZXRKenU4RjUxdzZ2TnFBQnowUm9uenNpT2ZEODhsN1dzCkZzRDVUWDNpZDd0dmhqS2EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
contexts:
  - context:
      cluster: garden-ai-trust
      user: oidc-login
      namespace: garden-ai-trust
    name: garden-ai-trust
current-context: garden-ai-trust
users:
  - name: oidc-login
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: kubectl
        args:
          - oidc-login
          - get-token
          - >-
            --oidc-issuer-url=https://portal.cc-two.showroom.apeirora.eu/keycloak/realms/operator
          - '--oidc-client-id=gardener'
          - '--oidc-extra-scope=email'
          - '--oidc-pkce-method=S256'
          - '--grant-type=authcode'
          - '--skip-open-browser'
          - '--listen-address=127.0.0.1:8000'
preferences: {}
