apiVersion: v1
items:
- apiVersion: cert.gardener.cloud/v1alpha1
  kind: Certificate
  metadata:
    annotations:
      cert.gardener.cloud/not-after: "2026-11-08T11:29:33Z"
      cert.gardener.cloud/not-before: "2026-08-10T11:29:34Z"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert.gardener.cloud/v1alpha1","kind":"Certificate","metadata":{"annotations":{},"name":"cert-p1","namespace":"platform-mesh-system"},"spec":{"dnsNames":["*.ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu"],"secretRef":{"name":"cert-p1","namespace":"platform-mesh-system"}}}
    creationTimestamp: "2026-08-10T11:10:27Z"
    generation: 1
    labels:
      cert.gardener.cloud/hash: 32cd0304f7b413a2300e147e4ab37451b130bad1f901fa92128f98d7
    name: cert-p1
    namespace: platform-mesh-system
    resourceVersion: "175478"
    uid: b96abc1f-79e8-405d-a694-968eba1591fd
  spec:
    dnsNames:
    - '*.ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu'
    secretRef:
      name: cert-p1
      namespace: platform-mesh-system
  status:
    conditions:
    - lastTransitionTime: "2026-08-10T12:28:05Z"
      message: ""
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    dnsNames:
    - '*.ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu'
    expirationDate: "2026-11-08T11:29:33Z"
    issuanceDate: "2026-08-10T11:29:34Z"
    issuerRef:
      cluster: default
      name: gardener
      namespace: shoot--ai-trust--ai-trust-1
    message: certificate (SN 6d:bb:94:3a:e0:2f:74:4c:45:5b:65:33:36:e0:42:f6:63:0)
      valid from 2026-08-10 11:29:34 +0000 UTC to 2026-11-08 11:29:33 +0000 UTC
    observedGeneration: 1
    renewalDate: "2026-10-09T11:29:33Z"
    state: Ready
- apiVersion: cert.gardener.cloud/v1alpha1
  kind: Certificate
  metadata:
    annotations:
      cert.gardener.cloud/not-after: "2026-11-08T10:15:44Z"
      cert.gardener.cloud/not-before: "2026-08-10T10:15:45Z"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert.gardener.cloud/v1alpha1","kind":"Certificate","metadata":{"annotations":{},"name":"cert-p2","namespace":"platform-mesh-system"},"spec":{"dnsNames":["ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu"],"secretRef":{"name":"cert-p2","namespace":"platform-mesh-system"}}}
    creationTimestamp: "2026-08-10T11:09:56Z"
    generation: 1
    labels:
      cert.gardener.cloud/hash: 8281e53cb0b8037522ab87b209e09291ab11acf0896bf46a1846e328
    name: cert-p2
    namespace: platform-mesh-system
    resourceVersion: "94703"
    uid: 6bdd3d9a-2a61-40c0-ba18-8ea062650067
  spec:
    dnsNames:
    - ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu
    secretRef:
      name: cert-p2
      namespace: platform-mesh-system
  status:
    conditions:
    - lastTransitionTime: "2026-08-10T11:14:18Z"
      message: ""
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    dnsNames:
    - ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu
    expirationDate: "2026-11-08T10:15:44Z"
    issuanceDate: "2026-08-10T10:15:45Z"
    issuerRef:
      cluster: default
      name: gardener
      namespace: shoot--ai-trust--ai-trust-1
    message: certificate (SN 59:29:79:9e:eb:37:5e:33:a1:b8:57:e4:60:42:f7:d1:ef:c)
      valid from 2026-08-10 10:15:45 +0000 UTC to 2026-11-08 10:15:44 +0000 UTC
    observedGeneration: 1
    renewalDate: "2026-10-09T10:15:44Z"
    state: Ready
- apiVersion: cert.gardener.cloud/v1alpha1
  kind: Certificate
  metadata:
    annotations:
      cert.gardener.cloud/not-after: "2028-11-12T11:19:08Z"
      cert.gardener.cloud/not-before: "2026-08-10T10:13:58Z"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert.gardener.cloud/v1alpha1","kind":"Certificate","metadata":{"annotations":{},"name":"domain-certificate","namespace":"platform-mesh-system"},"spec":{"dnsNames":["ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu","*.ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu"],"secretRef":{"name":"domain-certificate","namespace":"platform-mesh-system"}}}
    creationTimestamp: "2026-08-10T11:07:57Z"
    generation: 1
    labels:
      cert.gardener.cloud/hash: 62ac8078575dd3cd844e457ff75b3a8fa077bf4cdeb4074a5e3e1bd5
    name: domain-certificate
    namespace: platform-mesh-system
    resourceVersion: "102951"
    uid: c1e669b6-2b8b-4adc-aabb-4d2d1847409d
  spec:
    dnsNames:
    - ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu
    - '*.ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu'
    secretRef:
      name: domain-certificate
      namespace: platform-mesh-system
  status:
    conditions:
    - lastTransitionTime: "2026-08-10T11:12:29Z"
      message: ""
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    dnsNames:
    - ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu
    - '*.ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu'
    expirationDate: "2028-11-12T11:19:08Z"
    issuanceDate: "2026-08-10T10:13:58Z"
    issuerRef:
      cluster: default
      name: gardener
      namespace: shoot--ai-trust--ai-trust-1
    message: certificate (SN 14:82:6f:e4:ce:11:60:23:99:bd:93:50:08:e7:97:37:93:ec:f4:31)
      valid from 2026-08-10 11:19:08 +0000 UTC to 2028-11-12 11:19:08 +0000 UTC
    observedGeneration: 1
    renewalDate: "2028-10-13T11:19:08Z"
    state: Ready
kind: List
metadata:
  resourceVersion: ""
