apiVersion: v1
kind: Service
metadata:
  annotations:
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu,*.ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu
    dns.gardener.cloud/ttl: "120"
    loadbalancer.openstack.org/load-balancer-address: 130.214.18.166
    loadbalancer.openstack.org/load-balancer-id: b06b1eab-9afa-4087-9761-2ebfe2d88c33
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2026-08-10T11:53:30Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  - garden.dns.gardener.cloud/service-dns
  labels:
    app.kubernetes.io/instance: traefik-default
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-39.0.7_a021f37ddb42
    helm.toolkit.fluxcd.io/name: traefik
    helm.toolkit.fluxcd.io/namespace: platform-mesh-system
  name: traefik
  namespace: default
  resourceVersion: "199371"
  uid: f93a38b7-7bd7-4e15-8ef2-b104825dba6c
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 100.104.188.4
  clusterIPs:
  - 100.104.188.4
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    nodePort: 31019
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 31199
    port: 8443
    protocol: TCP
    targetPort: websecure
  - name: websecure-443
    nodePort: 30131
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik-default
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 130.214.18.166
      ipMode: VIP
