### OCIRepository traefik / traefik-crds / infra (platform-mesh-system)
--- ocirepository platform-mesh-system/traefik ---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  creationTimestamp: "2026-08-10T11:09:24Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  name: traefik
  namespace: platform-mesh-system
  resourceVersion: "85232"
  uid: c820a0cd-ad69-48d9-b7fc-982c5c64b4e7
spec:
  interval: 1m0s
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  provider: generic
  ref:
    tag: 39.0.7
  timeout: 60s
  url: oci://ghcr.io/platform-mesh/ocm/charts/traefik
status:
  artifact:
    digest: sha256:55a7384ae3a69af13e7dd7f898304a1f9890791e6712774635cd3a2df34da4c8
    lastUpdateTime: "2026-08-10T11:09:28Z"
    metadata:
      artifacthub.io/changes: "- \"feat(deps): update traefik docker tag to v3.6.12
        (v39.0)\"\n- \"chore(release): \U0001F680 publish v39.0.7\"\n"
      org.opencontainers.image.authors: mloiseleur (michel.loiseleur@traefik.io),
        darkweaver87 (remi.buisson@traefik.io), jnoordsij
      org.opencontainers.image.created: "2026-06-03T11:34:02Z"
      org.opencontainers.image.description: A Traefik based Kubernetes ingress controller
      org.opencontainers.image.source: https://github.com/traefik/traefik-helm-chart
      org.opencontainers.image.title: traefik
      org.opencontainers.image.url: https://traefik.io/
      org.opencontainers.image.version: 39.0.7
    path: ocirepository/platform-mesh-system/traefik/sha256:a021f37ddb425470864432f5c47495bd30699f74c3fa3fd2434ac56bc17d04a0.tar.gz
    revision: 39.0.7@sha256:a021f37ddb425470864432f5c47495bd30699f74c3fa3fd2434ac56bc17d04a0
    size: 317846
    url: http://source-controller.flux-system.svc.cluster.local./ocirepository/platform-mesh-system/traefik/sha256:a021f37ddb425470864432f5c47495bd30699f74c3fa3fd2434ac56bc17d04a0.tar.gz
  conditions:
  - lastTransitionTime: "2026-08-10T11:09:28Z"
    message: stored artifact for digest '39.0.7@sha256:a021f37ddb425470864432f5c47495bd30699f74c3fa3fd2434ac56bc17d04a0'
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-08-10T11:09:28Z"
    message: stored artifact for digest '39.0.7@sha256:a021f37ddb425470864432f5c47495bd30699f74c3fa3fd2434ac56bc17d04a0'
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: ArtifactInStorage
  observedGeneration: 1
  observedLayerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: http://source-controller.flux-system.svc.cluster.local./ocirepository/platform-mesh-system/traefik/latest.tar.gz
--- ocirepository platform-mesh-system/traefik-crds ---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  creationTimestamp: "2026-08-10T11:09:24Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  name: traefik-crds
  namespace: platform-mesh-system
  resourceVersion: "85183"
  uid: 96c9df3b-7d6b-4298-9a71-3e9b781b08fc
spec:
  interval: 1m0s
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  provider: generic
  ref:
    tag: 1.14.0
  timeout: 60s
  url: oci://ghcr.io/platform-mesh/ocm/charts/traefik-crds
status:
  artifact:
    digest: sha256:39750c0a3b7109d2bc5740fe8d057675812b45da08f26fd9ad3a6075a9f68706
    lastUpdateTime: "2026-08-10T11:09:27Z"
    metadata:
      artifacthub.io/changes: "- \"feat(CRDs)!: support Traefik Hub v3.19.0\"\n- \"docs(CRDs):
        improve note on deprecation\"\n- \"chore(release): \U0001F680 publish traefik
        39.0.0 and crds 1.14.0\"\n"
      org.opencontainers.image.authors: mloiseleur (michel.loiseleur@traefik.io),
        darkweaver87 (remi.buisson@traefik.io), jnoordsij
      org.opencontainers.image.created: "2026-06-03T15:21:48Z"
      org.opencontainers.image.description: A Traefik based Kubernetes ingress controller
      org.opencontainers.image.source: https://github.com/traefik/traefik-helm-chart
      org.opencontainers.image.title: traefik-crds
      org.opencontainers.image.url: https://traefik.io/
      org.opencontainers.image.version: 1.14.0
    path: ocirepository/platform-mesh-system/traefik-crds/sha256:d773701882ec39357fed7aad018147d5cb7e1b452b4235b8a148a9ae0f265ad9.tar.gz
    revision: 1.14.0@sha256:d773701882ec39357fed7aad018147d5cb7e1b452b4235b8a148a9ae0f265ad9
    size: 364800
    url: http://source-controller.flux-system.svc.cluster.local./ocirepository/platform-mesh-system/traefik-crds/sha256:d773701882ec39357fed7aad018147d5cb7e1b452b4235b8a148a9ae0f265ad9.tar.gz
  conditions:
  - lastTransitionTime: "2026-08-10T11:09:27Z"
    message: stored artifact for digest '1.14.0@sha256:d773701882ec39357fed7aad018147d5cb7e1b452b4235b8a148a9ae0f265ad9'
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-08-10T11:09:27Z"
    message: stored artifact for digest '1.14.0@sha256:d773701882ec39357fed7aad018147d5cb7e1b452b4235b8a148a9ae0f265ad9'
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: ArtifactInStorage
  observedGeneration: 1
  observedLayerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: http://source-controller.flux-system.svc.cluster.local./ocirepository/platform-mesh-system/traefik-crds/latest.tar.gz
--- ocirepository platform-mesh-system/infra ---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  creationTimestamp: "2026-08-10T11:09:28Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  name: infra
  namespace: platform-mesh-system
  resourceVersion: "85939"
  uid: 064996b9-57e8-4dbc-8aba-b1acca37a3e3
spec:
  interval: 1m0s
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  provider: generic
  ref:
    tag: 0.34.0
  timeout: 60s
  url: oci://ghcr.io/platform-mesh/helm-charts/infra
status:
  artifact:
    digest: sha256:d1a49c3bd0ea97e41cfce2e4c382a0edafa1662a1a6e1ae76f96131bd3409f69
    lastUpdateTime: "2026-08-10T11:09:39Z"
    path: ocirepository/platform-mesh-system/infra/sha256:63e8ca2f1f29f6cc21cdddaa6e5970eb281ac9cae86e0a820ebc1b532dc814b6.tar.gz
    revision: 0.34.0@sha256:63e8ca2f1f29f6cc21cdddaa6e5970eb281ac9cae86e0a820ebc1b532dc814b6
    size: 26177
    url: http://source-controller.flux-system.svc.cluster.local./ocirepository/platform-mesh-system/infra/sha256:63e8ca2f1f29f6cc21cdddaa6e5970eb281ac9cae86e0a820ebc1b532dc814b6.tar.gz
  conditions:
  - lastTransitionTime: "2026-08-10T11:09:39Z"
    message: stored artifact for digest '0.34.0@sha256:63e8ca2f1f29f6cc21cdddaa6e5970eb281ac9cae86e0a820ebc1b532dc814b6'
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-08-10T11:09:39Z"
    message: stored artifact for digest '0.34.0@sha256:63e8ca2f1f29f6cc21cdddaa6e5970eb281ac9cae86e0a820ebc1b532dc814b6'
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: ArtifactInStorage
  observedGeneration: 1
  observedLayerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: http://source-controller.flux-system.svc.cluster.local./ocirepository/platform-mesh-system/infra/latest.tar.gz
