--- tlsstore: 0 object(s) ---
--- tlsoption: 0 object(s) ---
--- middleware: 1 object(s) ---
apiVersion: v1
items:
- apiVersion: traefik.io/v1alpha1
  kind: Middleware
  metadata:
    annotations:
      meta.helm.sh/release-name: infra
      meta.helm.sh/release-namespace: platform-mesh-system
    creationTimestamp: "2026-08-10T11:10:31Z"
    generation: 2
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.toolkit.fluxcd.io/name: infra
      helm.toolkit.fluxcd.io/namespace: platform-mesh-system
    name: cors-header
    namespace: platform-mesh-system
    resourceVersion: "166751"
    uid: 811642cc-495a-431d-a6ed-3e2dba4dfe81
  spec:
    headers:
      accessControlAllowCredentials: true
      accessControlAllowHeaders:
      - '*'
      accessControlAllowMethods:
      - GET
      - OPTIONS
      - POST
      accessControlAllowOriginList:
      - http://localhost:4200
      - http://localhost:4300
      - http://*.localhost:4200
      - http://*.localhost:4300
      - http://sub.localhost:4300
      - https://ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu
      - https://*.ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu
      accessControlMaxAge: 100
      addVaryHeader: true
kind: List
metadata:
  resourceVersion: ""
--- ingressroute: 0 object(s) ---
--- ingressroutetcp: 0 object(s) ---
--- ingressrouteudp: 0 object(s) ---
--- serverstransport: 0 object(s) ---
--- serverstransporttcp: 0 object(s) ---
--- traefikservice: 0 object(s) ---
--- middlewaretcp: 0 object(s) ---
